version: '3.1'

services:
  docker-sanity:
    build: .
    image: docker-sanity
    command: yarn start
    expose:
      - 8000

  docker-sanity-tests:
    image: docker-sanity
    command: yarn test
    environment:
      APP_URL: http://docker-sanity:8000
    depends_on:
      - docker-sanity