version: '3.1'

services:
  tdd-ts-docker-starter:
    build: .
    image: tdd-ts-docker-starter
    command: yarn start
    expose:
      - 8000

  tdd-ts-docker-starter-tests:
    image: tdd-ts-docker-starter
    command: yarn test
    environment:
      APP_URL: http://tdd-ts-docker-starter:8000
    depends_on:
      - tdd-ts-docker-starter